/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface KevKevin {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface KevKevinAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'KevKevin': Components.KevKevin;
  }

  interface StencilIntrinsicElements {
    'kev-kevin': Components.KevKevinAttributes;
  }


  interface HTMLKevKevinElement extends Components.KevKevin, HTMLStencilElement {}
  var HTMLKevKevinElement: {
    prototype: HTMLKevKevinElement;
    new (): HTMLKevKevinElement;
  };

  interface HTMLElementTagNameMap {
    'kev-kevin': HTMLKevKevinElement
  }

  interface ElementTagNameMap {
    'kev-kevin': HTMLKevKevinElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
