/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ProfilePic {
    'alt_msg': string;
    'class_name': string;
    'user_name': string;
  }
  interface ProfilePicAttributes extends StencilHTMLAttributes {
    'alt_msg'?: string;
    'class_name'?: string;
    'user_name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ProfilePic': Components.ProfilePic;
  }

  interface StencilIntrinsicElements {
    'profile-pic': Components.ProfilePicAttributes;
  }


  interface HTMLProfilePicElement extends Components.ProfilePic, HTMLStencilElement {}
  var HTMLProfilePicElement: {
    prototype: HTMLProfilePicElement;
    new (): HTMLProfilePicElement;
  };

  interface HTMLElementTagNameMap {
    'profile-pic': HTMLProfilePicElement
  }

  interface ElementTagNameMap {
    'profile-pic': HTMLProfilePicElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
